// ---------------------------------------------------------------------------
// 12 sample listings. Replace title/price/area/image with your live inventory.
// Images live in /public/images and are already in WebP (1200x800).
// Keep alt text descriptive: it is read by Google Images and screen readers.
// ---------------------------------------------------------------------------

export const properties = [
  {
    id: 'plot-urban-estate',
    title: '150 Gaj Residential Plot, Urban Estate',
    type: 'Plot',
    deal: 'Sale',
    location: 'Urban Estate, Jind',
    price: '₹42 Lakh',
    size: '150 gaj (1350 sq.ft.)',
    image: '/images/plot-for-sale-urban-estate-jind.webp',
    alt: 'Residential plot for sale in Urban Estate, Jind with marked boundary',
    points: ['Clear registry, no dispute', 'Park facing, 30 ft road', 'Loan approved colony'],
  },
  {
    id: 'kothi-rohtak-road',
    title: '3 BHK Kothi, Rohtak Road',
    type: 'House',
    deal: 'Sale',
    location: 'Rohtak Road, Jind',
    price: '₹78 Lakh',
    size: '200 gaj, ground + 1',
    image: '/images/3bhk-kothi.webp',
    alt: 'Independent 3 BHK kothi for sale on Rohtak Road in Jind',
    points: ['Ready to move', 'Covered car parking', 'Borewell + municipal water'],
  },
  {
    id: 'flat-3bhk-jind',
    title: '3 BHK Flat in Gated Society',
    type: 'Flat',
    deal: 'Sale',
    location: 'Near Jind Bypass',
    price: '₹55 Lakh',
    size: '1450 sq.ft., 4th floor',
    image: '/images/3bhk-society.webp',
    alt: '3 BHK flat for sale in a gated society near Jind bypass',
    points: ['Lift + power backup', 'Gated with security', 'Bank loan available'],
  },
  {
    id: 'shop-bypass',
    title: 'Corner Shop on Main Bypass',
    type: 'Commercial',
    deal: 'Sale',
    location: 'Jind Bypass',
    price: '₹36 Lakh',
    size: '18 x 40 ft',
    image: '/images/corner-shop.webp',
    alt: 'Commercial shop for sale on the main bypass road in Jind',
    points: ['Highway frontage', 'Running market', 'High rental return'],
  },
  {
    id: 'plot-gohana-road',
    title: '200 Gaj Plot, Gohana Road',
    type: 'Plot',
    deal: 'Sale',
    location: 'Gohana Road, Jind',
    price: '₹51 Lakh',
    size: '200 gaj (1800 sq.ft.)',
    image: '/images/gohana-road.webp',
    alt: 'Residential plot for sale on Gohana Road in Jind, Haryana',
    points: ['Corner plot', 'Sewer + street light ready', 'Registry same day'],
  },
  {
    id: 'house-safidon-road',
    title: '2 BHK Independent House',
    type: 'House',
    deal: 'Sale',
    location: 'Safidon Road, Jind',
    price: '₹46 Lakh',
    size: '125 gaj',
    image: '/images/2bhk-independent.webp',
    alt: 'Two bedroom independent house for sale on Safidon Road, Jind',
    points: ['Newly built', 'Modular kitchen', 'School within 1 km'],
  },
  {
    id: 'flat-rent-2bhk',
    title: '2 BHK Flat for Family',
    type: 'Flat',
    deal: 'Rent',
    location: 'Urban Estate, Jind',
    price: '₹11,000 / month',
    size: '1050 sq.ft., semi-furnished',
    image: '/images/2bhk-family.webp',
    alt: '2 BHK flat on rent in Jind for a family, semi furnished',
    points: ['Family or working couple', '2 months security', 'Immediate possession'],
  },
  {
    id: 'showroom-patiala-chowk',
    title: 'Showroom near Patiala Chowk',
    type: 'Commercial',
    deal: 'Rent',
    location: 'Patiala Chowk, Jind',
    price: '₹35,000 / month',
    size: '900 sq.ft. hall',
    image: '/images/showroom.webp',
    alt: 'Showroom on rent near Patiala Chowk in Jind city',
    points: ['Glass front', 'Heavy footfall', 'Ideal for brand outlet'],
  },
  {
    id: 'land-near-jind',
    title: '4 Acre Agricultural Land',
    type: 'Land',
    deal: 'Sale',
    location: '9 km from Jind city',
    price: '₹28 Lakh / acre',
    size: '4 acres, tubewell',
    image: '/images/land.webp',
    alt: 'Agricultural land for sale near Jind with tubewell and road access',
    points: ['Road touch', 'Tubewell + motor', 'Good for farmhouse'],
  },
  {
    id: 'duplex-kothi',
    title: 'Duplex Kothi with Lawn',
    type: 'House',
    deal: 'Sale',
    location: 'Defence Colony, Jind',
    price: '₹1.15 Crore',
    size: '300 gaj duplex',
    image: '/images/duplex-kothi-for-sale-jind.webp',
    alt: 'Duplex kothi with lawn for sale in Defence Colony, Jind',
    points: ['4 bedrooms with attached bath', 'Front lawn + parking', 'Premium colony'],
  },
  {
    id: 'builder-floor',
    title: 'Builder Floor, 2nd Level',
    type: 'Flat',
    deal: 'Sale',
    location: 'Hansi Road, Jind',
    price: '₹33 Lakh',
    size: '2 BHK, 900 sq.ft.',
    image: '/images/builder-floor-for-sale-in-jind.webp',
    alt: 'Two BHK builder floor for sale on Hansi Road in Jind',
    points: ['Budget friendly', 'Separate entry', 'Market walking distance'],
  },
  {
    id: 'office-rent',
    title: 'Office Space, First Floor',
    type: 'Commercial',
    deal: 'Rent',
    location: 'Rani Talab, Jind',
    price: '₹18,000 / month',
    size: '700 sq.ft., 3 cabins',
    image: '/images/office-space-on-rent-in-jind.webp',
    alt: 'Office space on rent at Rani Talab in Jind with three cabins',
    points: ['3 cabins + pantry', 'Parking space', 'Ready for coaching or clinic'],
  },
];

export const propertyTypes = ['Plot', 'House', 'Flat', 'Commercial', 'Land'];
